name: finance_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  crypto: ^3.0.3
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: any
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  timezone: ^0.9.4
  

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true
